import Head from "next/head";
import Footer from "~/components/layoutSections/Footer";
import { useUser } from "@clerk/nextjs";
import { useRouter } from "next/router";
import Link from "next/link";
import {
  Bars3Icon,
  HomeIcon,
  PencilSquareIcon,
  PlusCircleIcon,
  //PuzzlePieceIcon,
} from "@heroicons/react/24/outline";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = useUser();
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Chess Notes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen min-h-fit w-screen overflow-x-hidden bg-zinc-50 text-black">
        {/* 
        Navbar to be displayed before main content
        Rationale that this isnt in a new file is because DaisyUI
        Requires the incorperation of {children} for body content 
        In the drawer section
        */}
        <div className="drawer z-30 text-zinc-50">
          <input
            id="navigationDrawer"
            type="checkbox"
            className="drawer-toggle"
          />
          <div className="drawer-content flex flex-col">
            {/* Navbar */}
            <div className="navbar sticky top-0 z-10 w-full bg-slate-900">
              <div className="mx-4 flex-1 text-2xl lg:text-4xl">
                Chess Notes
              </div>
              <div className="mx-4 flex-none lg:hidden">
                <label
                  htmlFor="navigationDrawer"
                  className="btn-ghost btn-square btn"
                >
                  <Bars3Icon className="h-8 w-8" />
                </label>
              </div>
              <div className="mx-4 hidden flex-none lg:block">
                <ul className="menu menu-horizontal gap-4">
                  {user.isSignedIn ? (
                    <>
                      <Link
                        className={`duration-400 relative rounded-lg bg-emerald-500 px-5 py-1.5  text-xl transition hover:scale-105 hover:cursor-pointer hover:bg-emerald-400 hover:text-zinc-50 ${
                          router.pathname === "/user"
                            ? "bg-emerald-400 text-zinc-50"
                            : ""
                        }`}
                        href={"/user"}
                      >
                        {router.pathname === "/user" && (
                          <>
                            <span className="absolute right-0 top-0 -mt-1 h-3 w-3 animate-ping rounded-full bg-emerald-400 opacity-75"></span>
                            <span className="absolute right-0 top-0 -mt-1 h-3 w-3 rounded-full bg-emerald-400"></span>
                          </>
                        )}
                        <li>Home</li>
                      </Link>
                      {/* 
                      <Link
                        className={`duration-400 relative rounded-lg bg-emerald-500 px-5 py-1.5  text-xl transition hover:scale-105 hover:cursor-pointer hover:bg-emerald-400 hover:text-zinc-50 ${
                          router.pathname === "/games"
                            ? "bg-emerald-400 text-zinc-50"
                            : ""
                        }`}
                        href={"/games"}
                      >
                        {router.pathname === "/games" && (
                          <>
                            <span className="absolute right-0 top-0 -mt-1 h-3 w-3 animate-ping rounded-full bg-emerald-400 opacity-75"></span>
                            <span className="absolute right-0 top-0 -mt-1 h-3 w-3 rounded-full bg-emerald-400"></span>
                          </>
                        )}
                        <li>My games</li>
                      </Link>
                    */}
                      <Link
                        className={`duration-400 relative rounded-lg bg-emerald-500 px-5 py-1.5  text-xl transition hover:scale-105 hover:cursor-pointer hover:bg-emerald-400 hover:text-zinc-50 ${
                          router.pathname === "/notes"
                            ? "rounded-lg bg-emerald-400 text-zinc-50"
                            : ""
                        }`}
                        href={"/notes"}
                      >
                        {router.pathname === "/notes" && (
                          <>
                            <span className="absolute right-0 top-0 -mt-1 h-3 w-3 animate-ping rounded-full bg-emerald-400 opacity-75"></span>
                            <span className="absolute right-0 top-0 -mt-1 h-3 w-3 rounded-full bg-emerald-400"></span>
                          </>
                        )}
                        <li>My Notes</li>
                      </Link>
                      <Link
                        className={`duration-400 relative rounded-lg bg-emerald-500 px-5 py-1.5  text-xl transition hover:scale-105 hover:cursor-pointer hover:bg-emerald-400 hover:text-zinc-50 ${
                          router.pathname === "/new-analysis"
                            ? "bg-emerald-400 text-zinc-50"
                            : ""
                        }`}
                        href={"/new-analysis"}
                      >
                        {router.pathname === "/new-analysis" && (
                          <>
                            <span className="absolute right-0 top-0 -mt-1 h-3 w-3 animate-ping rounded-full bg-emerald-400 opacity-75"></span>
                            <span className="absolute right-0 top-0 -mt-1 h-3 w-3 rounded-full bg-emerald-400"></span>
                          </>
                        )}
                        <li>New Analysis</li>
                      </Link>
                    </>
                  ) : (
                    <>
                      <Link href="/user-sign-up" className="h-full w-full">
                        <li className="duration-400 w-fit rounded-lg bg-emerald-500 px-5 py-1.5 text-base transition hover:scale-105 hover:cursor-pointer hover:bg-emerald-400 hover:text-zinc-50">
                          Sign Up!
                        </li>
                      </Link>
                    </>
                  )}
                </ul>
              </div>
            </div>
            <div className="h-fit min-h-screen w-screen">
              {children}
              <Footer />
            </div>
          </div>
          <div className="drawer-side">
            <label
              htmlFor="navigationDrawer"
              className="drawer-overlay"
            ></label>
            <ul className="menu flex h-full w-80 flex-col gap-6 bg-slate-900 ">
              <li className="flex-none p-2 text-3xl lg:text-4xl">
                Chess Notes
              </li>
              {user.isSignedIn ? (
                <>
                  <Link
                    href={"/user"}
                    className="flex cursor-pointer flex-row items-start gap-2 rounded-lg px-2 py-1 hover:bg-slate-950"
                  >
                    <HomeIcon className="h-7 w-7 text-emerald-300" />
                    <li className="text-2xl">Home</li>
                  </Link>
                  {/*
                    
                  <Link
                    href={"/games"}
                    className="flex cursor-pointer flex-row items-start gap-2 rounded-lg px-2 py-1 hover:bg-slate-950"
                  >
                    <PuzzlePieceIcon className="h-7 w-7 text-emerald-300" />
                    <li className="text-2xl">My Games</li>
                  </Link>
                  */}
                  <Link
                    href={"/notes"}
                    className="flex cursor-pointer flex-row items-start gap-2 rounded-lg px-2 py-1 hover:bg-slate-950"
                  >
                    <PencilSquareIcon className="h-7 w-7 text-emerald-300" />
                    <li className="text-2xl">My Notes</li>
                  </Link>
                  <Link
                    href={"/new-analysis"}
                    className="flex cursor-pointer flex-row items-start gap-2 rounded-lg px-2 py-1 hover:bg-slate-950"
                  >
                    <PlusCircleIcon className="h-7 w-7 text-emerald-300" />
                    <li className="text-2xl">New Analysis</li>
                  </Link>
                </>
              ) : (
                <>
                  <Link
                    href="/user-sign-up"
                    className="flex cursor-pointer flex-row items-start gap-2 rounded-lg p-2 hover:bg-slate-950"
                  >
                    <PlusCircleIcon className="h-7 w-7 text-emerald-300" />
                    <li className="text-2xl">Sign Up!</li>
                  </Link>
                </>
              )}
            </ul>
          </div>
        </div>
      </main>
    </>
  );
}
